// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WompattiApi.Models
{
    public partial class User
    {
        public User()
        {
            Answer = new HashSet<Answer>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Username { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Answer> Answer { get; set; }
    }
}